let billRes = {
  "1.重要系统": [
    {
      data: [
        {
          content:
            "\n           总量:252台\n                可用资源:\n             CPU:6960c,内存:22176G,文件系统:202271.54G\n                    已使用:\nCPU:1479.63c,占比:21.26%\n                     内存:7751.72G,占比:34.96%\n                        文件系统:84609.39G,占比:41.83%\n",
          title: "虚拟机资源账单",
        },
        {
          content:
            "\n           总量:252台\n                可用资源:\n             CPU:6960c,内存:22176G,文件系统:202271.54G\n                    已使用:\nCPU:1479.63c,占比:21.26%\n                     内存:7751.72G,占比:34.96%\n                        文件系统:84609.39G,占比:41.83%\n",
          title: "物理机资源账单",
        },
        {
          content:
            "\n                    合计17套集群资源使用率低,阈值30%。\n                     集群HAPROXY-act_ht_haproxy_5:设备数:2\n\n                               可用资源:\n                        CPU:32c,内存:128G,文件系统:401.8G\n                        已使用:\n                   CPU:0.31c,占比:0.98%\n                   内存:26.47G,占比:20.68%\n                   文件系统:6.46G,占比:1.61%\n                  集群HAPROXY-act_ht_haproxy_7:设备数:2\n\n                     可用资源:\n                CPU:16c,内存:32G,文件系统:321.84G\n                  已使用:\n                         CPU:2.13c,占比:13.34%\n                        内存:8.49G,占比:26.52%\n                      文件系统:2.44G,占比:0.76%\n                  集群HAPROXY-act_ht_haproxy_8:设备数:2\n\n                  可用资源:\n                      CPU:16c,内存:32G,文件系统:321.84G\n                     已使用:\n                   CPU:2.15c,占比:13.46%\n                     内存:8.49G,占比:26.53%\n                          文件系统:2.44G,占比:0.76%\n                        集群HAPROXY-act_ht_haproxy_9:设备数:2\n\n                             可用资源:\n                     CPU:16c,内存:32G,文件系统:321.84G\n                      已使用:\n                    CPU:2.22c,占比:13.87%...",
          title: "低资源使用率明细",
        },
      ],
      systemName: "S新核心_账户处理",
    },
  ],
  "2.关键系统": [
    {
      data: [
        {
          content:
            "\n           总量:252台\n                可用资源:\n             CPU:6960c,内存:22176G,文件系统:202271.54G\n                    已使用:\nCPU:1479.63c,占比:21.26%\n                     内存:7751.72G,占比:34.96%\n                        文件系统:84609.39G,占比:41.83%\n",
          title: "虚拟机资源账单",
        },
        {
          content:
            "\n           总量:252台\n                可用资源:\n             CPU:6960c,内存:22176G,文件系统:202271.54G\n                    已使用:\nCPU:1479.63c,占比:21.26%\n                     内存:7751.72G,占比:34.96%\n                        文件系统:84609.39G,占比:41.83%\n",
          title: "物理机资源账单",
        },
        {
          content:
            "\n                    合计17套集群资源使用率低,阈值30%。\n                     集群HAPROXY-act_ht_haproxy_5:设备数:2\n\n                               可用资源:\n                        CPU:32c,内存:128G,文件系统:401.8G\n                        已使用:\n                   CPU:0.31c,占比:0.98%\n                   内存:26.47G,占比:20.68%\n                   文件系统:6.46G,占比:1.61%\n                  集群HAPROXY-act_ht_haproxy_7:设备数:2\n\n                     可用资源:\n                CPU:16c,内存:32G,文件系统:321.84G\n                  已使用:\n                         CPU:2.13c,占比:13.34%\n                        内存:8.49G,占比:26.52%\n                      文件系统:2.44G,占比:0.76%\n                  集群HAPROXY-act_ht_haproxy_8:设备数:2\n\n                  可用资源:\n                      CPU:16c,内存:32G,文件系统:321.84G\n                     已使用:\n                   CPU:2.15c,占比:13.46%\n                     内存:8.49G,占比:26.53%\n                          文件系统:2.44G,占比:0.76%\n                        集群HAPROXY-act_ht_haproxy_9:设备数:2\n\n                             可用资源:\n                     CPU:16c,内存:32G,文件系统:321.84G\n                      已使用:\n                    CPU:2.22c,占比:13.87%...",
          title: "低资源使用率明细",
        },
      ],
      systemName: "S数据服务网关",
    },
  ],
};

let systemProfileRes = {
  基础信息: {
    主机房: "北京东坝机房",
    数据中心: [
      "合肥灾备机房",
      "北京东坝机房",
      "合肥库房",
      "北京南法信机房",
      "深圳南湾机房",
      "深圳五联机房",
      "深圳五联机房1",
      "深圳五联机房2",
      "深圳五联机房3",
    ],
    系统名: "s新核心_数据&应用服务",
    系统简介:
      "提供以查询处理和文件处理等为核心的交易驱动型业务系统，主要包括产品服务、营销支撑、运营支撑、发卡与用卡、消息服务、账单查询与计算服务、风险服务、数据采集等十几个子模块",
    系统重要性级别: "A+",
    所属集群: "应用/dasp-app-mgr-d5c7",
  },
  组件拓扑: {
    CANAL: {
      "bjb-dasp-canal-kzx": [
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0001",
          idc: "BJ-NFX",
          ip: "26.131.162.1",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0002",
          idc: "BJ-NFX",
          ip: "26.131.162.2",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0003",
          idc: "BJ-NFX",
          ip: "26.131.162.3",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0004",
          idc: "BJ-NFX",
          ip: "26.131.162.4",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0005",
          idc: "BJ-NFX",
          ip: "26.131.162.5",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0006",
          idc: "BJ-NFX",
          ip: "26.131.162.6",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0007",
          idc: "BJ-NFX",
          ip: "26.131.162.7",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0008",
          idc: "BJ-NFX",
          ip: "26.131.162.8",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0009",
          idc: "BJ-NFX",
          ip: "26.131.162.9",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0010",
          idc: "BJ-NFX",
          ip: "26.131.162.10",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0011",
          idc: "BJ-NFX",
          ip: "26.131.162.11",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0012",
          idc: "BJ-NFX",
          ip: "26.131.162.12",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0013",
          idc: "BJ-NFX",
          ip: "26.131.162.13",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0014",
          idc: "BJ-NFX",
          ip: "26.131.162.14",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0015",
          idc: "BJ-NFX",
          ip: "26.131.162.15",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0016",
          idc: "BJ-NFX",
          ip: "26.131.162.16",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0017",
          idc: "BJ-NFX",
          ip: "26.131.162.17",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0018",
          idc: "BJ-NFX",
          ip: "26.131.162.18",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0019",
          idc: "BJ-NFX",
          ip: "26.131.162.19",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0020",
          idc: "BJ-NFX",
          ip: "26.131.162.20",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0021",
          idc: "BJ-NFX",
          ip: "26.131.162.21",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0022",
          idc: "BJ-NFX",
          ip: "26.131.162.22",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0023",
          idc: "BJ-NFX",
          ip: "26.131.162.23",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0024",
          idc: "BJ-NFX",
          ip: "26.131.162.24",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0025",
          idc: "BJ-NFX",
          ip: "26.131.162.25",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0026",
          idc: "BJ-NFX",
          ip: "26.131.162.26",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0027",
          idc: "BJ-NFX",
          ip: "26.131.162.27",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0028",
          idc: "BJ-NFX",
          ip: "26.131.162.28",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0029",
          idc: "BJ-NFX",
          ip: "26.131.162.29",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0030",
          idc: "BJ-NFX",
          ip: "26.131.162.30",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0031",
          idc: "BJ-NFX",
          ip: "26.131.162.31",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0032",
          idc: "BJ-NFX",
          ip: "26.131.162.32",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0033",
          idc: "BJ-NFX",
          ip: "26.131.162.33",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0034",
          idc: "BJ-NFX",
          ip: "26.131.162.34",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0035",
          idc: "BJ-NFX",
          ip: "26.131.162.35",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0036",
          idc: "BJ-NFX",
          ip: "26.131.162.36",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0037",
          idc: "BJ-NFX",
          ip: "26.131.162.37",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0038",
          idc: "BJ-NFX",
          ip: "26.131.162.38",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0039",
          idc: "BJ-NFX",
          ip: "26.131.162.39",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0040",
          idc: "BJ-NFX",
          ip: "26.131.162.40",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0041",
          idc: "BJ-NFX",
          ip: "26.131.162.41",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0042",
          idc: "BJ-NFX",
          ip: "26.131.162.42",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0043",
          idc: "BJ-NFX",
          ip: "26.131.162.43",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0044",
          idc: "BJ-NFX",
          ip: "26.131.162.44",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0045",
          idc: "BJ-NFX",
          ip: "26.131.162.45",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0046",
          idc: "BJ-NFX",
          ip: "26.131.162.46",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0047",
          idc: "BJ-NFX",
          ip: "26.131.162.47",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0048",
          idc: "BJ-NFX",
          ip: "26.131.162.48",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0049",
          idc: "BJ-NFX",
          ip: "26.131.162.49",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0050",
          idc: "BJ-NFX",
          ip: "26.131.162.50",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0051",
          idc: "BJ-NFX",
          ip: "26.131.162.51",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0052",
          idc: "BJ-NFX",
          ip: "26.131.162.52",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0053",
          idc: "BJ-NFX",
          ip: "26.131.162.53",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0054",
          idc: "BJ-NFX",
          ip: "26.131.162.54",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0055",
          idc: "BJ-NFX",
          ip: "26.131.162.55",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0056",
          idc: "BJ-NFX",
          ip: "26.131.162.56",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0057",
          idc: "BJ-NFX",
          ip: "26.131.162.57",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0058",
          idc: "BJ-NFX",
          ip: "26.131.162.58",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0059",
          idc: "BJ-NFX",
          ip: "26.131.162.59",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0060",
          idc: "BJ-NFX",
          ip: "26.131.162.60",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0061",
          idc: "BJ-NFX",
          ip: "26.131.162.61",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0062",
          idc: "BJ-NFX",
          ip: "26.131.162.62",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0063",
          idc: "BJ-NFX",
          ip: "26.131.162.63",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0064",
          idc: "BJ-NFX",
          ip: "26.131.162.64",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0065",
          idc: "BJ-NFX",
          ip: "26.131.162.65",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0066",
          idc: "BJ-NFX",
          ip: "26.131.162.66",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0067",
          idc: "BJ-NFX",
          ip: "26.131.162.67",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0068",
          idc: "BJ-NFX",
          ip: "26.131.162.68",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0069",
          idc: "BJ-NFX",
          ip: "26.131.162.69",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0070",
          idc: "BJ-NFX",
          ip: "26.131.162.70",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0071",
          idc: "BJ-NFX",
          ip: "26.131.162.71",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0072",
          idc: "BJ-NFX",
          ip: "26.131.162.72",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0073",
          idc: "BJ-NFX",
          ip: "26.131.162.73",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0074",
          idc: "BJ-NFX",
          ip: "26.131.162.74",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0075",
          idc: "BJ-NFX",
          ip: "26.131.162.75",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0076",
          idc: "BJ-NFX",
          ip: "26.131.162.76",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0077",
          idc: "BJ-NFX",
          ip: "26.131.162.77",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0078",
          idc: "BJ-NFX",
          ip: "26.131.162.78",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0079",
          idc: "BJ-NFX",
          ip: "26.131.162.79",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjb-dasp-canal-kzx-0080",
          idc: "BJ-NFX",
          ip: "26.131.162.80",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "bjc-dasp-canal-kzx": [
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "bjc-dasp-canal-kzx-0065",
          idc: "BJ-DB",
          ip: "26.131.162.65",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "hfa-dasp-canal-kzx": [
        {
          component: "dasp-plat-canal-server",
          cpu: "32",
          hostname: "hfa-dasp-canal-kzx-0066",
          idc: "HF",
          ip: "10.45.12.66",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
    },
    ES: {
      "bjb-dasp-es-kzx": [
        {
          component: "dasp-plat-es-node",
          cpu: "16",
          hostname: "bjb-dasp-es-kzx-0101",
          idc: "BJ-NFX",
          ip: "26.131.163.101",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-es-node",
          cpu: "16",
          hostname: "bjb-dasp-es-kzx-0102",
          idc: "BJ-NFX",
          ip: "26.131.163.102",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "bjc-dasp-es-kzx": [
        {
          component: "dasp-plat-es-node",
          cpu: "16",
          hostname: "bjc-dasp-es-kzx-0103",
          idc: "BJ-DB",
          ip: "26.131.163.103",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "hfa-dasp-es-kzx": [
        {
          component: "dasp-plat-es-node",
          cpu: "16",
          hostname: "hfa-dasp-es-kzx-0104",
          idc: "HF",
          ip: "10.45.13.104",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
    },
    GREATDB: {
      "bjb-dasp-greatdb-kzx": [
        {
          component: "dasp-plat-greatdb-node",
          cpu: "64",
          hostname: "bjb-dasp-greatdb-kzx-0201",
          idc: "BJ-NFX",
          ip: "26.131.164.201",
          memory: 256,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "bjc-dasp-greatdb-kzx": [
        {
          component: "dasp-plat-greatdb-node",
          cpu: "64",
          hostname: "bjc-dasp-greatdb-kzx-0202",
          idc: "BJ-DB",
          ip: "26.131.164.202",
          memory: 256,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "hfa-dasp-greatdb-kzx": [
        {
          component: "dasp-plat-greatdb-node",
          cpu: "64",
          hostname: "hfa-dasp-greatdb-kzx-0203",
          idc: "HF",
          ip: "10.45.14.203",
          memory: 256,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
    },
    HADOOP: {
      "bjb-dasp-hadoop-kzx": [
        {
          component: "dasp-plat-hadoop-datanode",
          cpu: "32",
          hostname: "bjb-dasp-hadoop-kzx-0301",
          idc: "BJ-NFX",
          ip: "26.131.165.301",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-hadoop-namenode",
          cpu: "32",
          hostname: "bjb-dasp-hadoop-kzx-0302",
          idc: "BJ-NFX",
          ip: "26.131.165.302",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "hfa-dasp-hadoop-kzx": [
        {
          component: "dasp-plat-hadoop-datanode",
          cpu: "32",
          hostname: "hfa-dasp-hadoop-kzx-0303",
          idc: "HF",
          ip: "10.45.15.303",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
    },
    HAPROXY: {
      dasp_ht_haproxy_4: [
        {
          component: "dasp-plat-haproxy",
          cpu: "8",
          hostname: "dasp-ht-haproxy-4",
          idc: "BJ-NFX",
          ip: "26.131.170.4",
          memory: 16,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      dasp_ht_haproxy_5: [
        {
          component: "dasp-plat-haproxy",
          cpu: "8",
          hostname: "dasp-ht-haproxy-5",
          idc: "BJ-NFX",
          ip: "26.131.170.5",
          memory: 16,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      dasp_cym_haproxy_4: [
        {
          component: "dasp-plat-haproxy",
          cpu: "8",
          hostname: "dasp-cym-haproxy-4",
          idc: "BJ-DB",
          ip: "26.131.170.6",
          memory: 16,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      dasp_cym_haproxy_8: [
        {
          component: "dasp-plat-haproxy",
          cpu: "8",
          hostname: "dasp-cym-haproxy-8",
          idc: "BJ-DB",
          ip: "26.131.170.7",
          memory: 16,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
    },
    KAFKA: {
      "bjb-dasp-kafka-kzx": [
        {
          component: "dasp-plat-kafka-broker",
          cpu: "16",
          hostname: "bjb-dasp-kafka-kzx-0401",
          idc: "BJ-NFX",
          ip: "26.131.166.401",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-kafka-broker",
          cpu: "16",
          hostname: "bjb-dasp-kafka-kzx-0402",
          idc: "BJ-NFX",
          ip: "26.131.166.402",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "bjc-dasp-kafka-kzx": [
        {
          component: "dasp-plat-kafka-broker",
          cpu: "16",
          hostname: "bjc-dasp-kafka-kzx-0403",
          idc: "BJ-DB",
          ip: "26.131.166.403",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "hfa-dasp-kafka-kzx": [
        {
          component: "dasp-plat-kafka-broker",
          cpu: "16",
          hostname: "hfa-dasp-kafka-kzx-0404",
          idc: "HF",
          ip: "10.45.16.404",
          memory: 64,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
    },
    MYSQL: {
      "bjb-dasp-mysql-kzx": [
        {
          component: "dasp-plat-mysql-master",
          cpu: "64",
          hostname: "bjb-dasp-mysql-kzx-0501",
          idc: "BJ-NFX",
          ip: "26.131.167.501",
          memory: 256,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-mysql-slave",
          cpu: "64",
          hostname: "bjb-dasp-mysql-kzx-0502",
          idc: "BJ-NFX",
          ip: "26.131.167.502",
          memory: 256,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "bjc-dasp-mysql-kzx": [
        {
          component: "dasp-plat-mysql-master",
          cpu: "64",
          hostname: "bjc-dasp-mysql-kzx-0503",
          idc: "BJ-DB",
          ip: "26.131.167.503",
          memory: 256,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "hfa-dasp-mysql-kzx": [
        {
          component: "dasp-plat-mysql-slave",
          cpu: "64",
          hostname: "hfa-dasp-mysql-kzx-0504",
          idc: "HF",
          ip: "10.45.17.504",
          memory: 256,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
    },
    NGINX: {
      "bjb-dasp-nginx-kzx": [
        {
          component: "dasp-plat-nginx",
          cpu: "8",
          hostname: "bjb-dasp-nginx-kzx-0601",
          idc: "BJ-NFX",
          ip: "26.131.168.601",
          memory: 16,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "bjc-dasp-nginx-kzx": [
        {
          component: "dasp-plat-nginx",
          cpu: "8",
          hostname: "bjc-dasp-nginx-kzx-0602",
          idc: "BJ-DB",
          ip: "26.131.168.602",
          memory: 16,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "hfa-dasp-nginx-kzx": [
        {
          component: "dasp-plat-nginx",
          cpu: "8",
          hostname: "hfa-dasp-nginx-kzx-0603",
          idc: "HF",
          ip: "10.45.18.603",
          memory: 16,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
    },
    ZOOKEEPER: {
      "bjb-dasp-zk-kzx": [
        {
          component: "dasp-plat-zookeeper",
          cpu: "8",
          hostname: "bjb-dasp-zk-kzx-0701",
          idc: "BJ-NFX",
          ip: "26.131.169.701",
          memory: 32,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "bjc-dasp-zk-kzx": [
        {
          component: "dasp-plat-zookeeper",
          cpu: "8",
          hostname: "bjc-dasp-zk-kzx-0702",
          idc: "BJ-DB",
          ip: "26.131.169.702",
          memory: 32,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "hfa-dasp-zk-kzx": [
        {
          component: "dasp-plat-zookeeper",
          cpu: "8",
          hostname: "hfa-dasp-zk-kzx-0703",
          idc: "HF",
          ip: "10.45.19.703",
          memory: 32,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
    },
    容器云: {
      "bjb-dasp-k8s-kzx": [
        {
          component: "dasp-plat-k8s-master",
          cpu: "32",
          hostname: "bjb-dasp-k8s-kzx-master01",
          idc: "BJ-NFX",
          ip: "26.131.160.101",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-k8s-node",
          cpu: "32",
          hostname: "bjb-dasp-k8s-kzx-node01",
          idc: "BJ-NFX",
          ip: "26.131.160.102",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-k8s-node",
          cpu: "32",
          hostname: "bjb-dasp-k8s-kzx-node02",
          idc: "BJ-NFX",
          ip: "26.131.160.103",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "bjc-dasp-k8s-kzx": [
        {
          component: "dasp-plat-k8s-master",
          cpu: "32",
          hostname: "bjc-dasp-k8s-kzx-master01",
          idc: "BJ-DB",
          ip: "26.131.160.201",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
        {
          component: "dasp-plat-k8s-node",
          cpu: "32",
          hostname: "bjc-dasp-k8s-kzx-node01",
          idc: "BJ-DB",
          ip: "26.131.160.202",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "hfa-dasp-k8s-kzx": [
        {
          component: "dasp-plat-k8s-node",
          cpu: "32",
          hostname: "hfa-dasp-k8s-kzx-node01",
          idc: "HF",
          ip: "10.45.20.301",
          memory: 128,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
    },
    应用: {
      "dasp-azkaban-mgr-4d86": [
        {
          component: "dasp-app-azkaban-mgr",
          cpu: "16",
          hostname: "dasp-azkaban-mgr-4d86",
          idc: "BJ-NFX",
          ip: "26.131.171.101",
          memory: 32,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "dasp-app-mgr-d5c7": [
        {
          component: "dasp-app-mgr",
          cpu: "16",
          hostname: "dasp-app-mgr-d5c7",
          idc: "BJ-NFX",
          ip: "26.131.171.102",
          memory: 32,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "bjc-dasp-mgr-7384": [
        {
          component: "dasp-app-mgr",
          cpu: "16",
          hostname: "bjc-dasp-mgr-7384",
          idc: "BJ-DB",
          ip: "26.131.171.103",
          memory: 32,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
      "bjc-dasp-mgr-3174": [
        {
          component: "dasp-app-mgr",
          cpu: "16",
          hostname: "bjc-dasp-mgr-3174",
          idc: "BJ-DB",
          ip: "26.131.171.104",
          memory: 32,
          mtype: "V",
          os: "Kylin Linux Advanced Server release V10 (Tercel)",
        },
      ],
    },
    微服务: {
      "BJ-DB@auth-adapt-mcd": [
        {
          limitCPU: 4,
          limitMemory: 8.192,
          replica: 2,
          serviceName: "auth-adapt-mcd",
        },
      ],
      "BJ-DB@auth-service-pay": [
        {
          limitCPU: 4,
          limitMemory: 8.192,
          replica: 3,
          serviceName: "auth-service-pay020",
        },
      ],
      "BJ-DB@auth-service-switchadapt": [
        {
          limitCPU: 4,
          limitMemory: 8.192,
          replica: 3,
          serviceName: "auth-service-switchadapt",
        },
      ],
    },
    测试: {
      测试一: [
        {
          a: 1,
          b: 2,
        },
        {
          a: 3,
          b: 4,
        },
        {
          a: 5,
          b: 6,
        },
      ],
    },
  },
  链路: [
    {
      fnode: "NGINX/bjb-dasp-nginx-kzx",
      snode: "HAPROXY/dasp_ht_haproxy_4",
    },
    {
      fnode: "NGINX/bjc-dasp-nginx-kzx",
      snode: "HAPROXY/dasp_cym_haproxy_4",
    },
    {
      fnode: "NGINX/hfa-dasp-nginx-kzx",
      snode: "HAPROXY/dasp_ht_haproxy_5",
    },
    {
      fnode: "HAPROXY/dasp_ht_haproxy_4",
      snode: "应用/dasp-azkaban-mgr-4d86",
    },
    {
      fnode: "HAPROXY/dasp_ht_haproxy_5",
      snode: "应用/dasp-app-mgr-d5c7",
    },
    {
      fnode: "HAPROXY/dasp_cym_haproxy_4",
      snode: "应用/bjc-dasp-mgr-7384",
    },
    {
      fnode: "HAPROXY/dasp_cym_haproxy_8",
      snode: "应用/bjc-dasp-mgr-3174",
    },
    {
      fnode: "应用/dasp-app-mgr-d5c7",
      snode: "容器云/bjb-dasp-k8s-kzx",
    },
    {
      fnode: "应用/bjc-dasp-mgr-7384",
      snode: "容器云/bjc-dasp-k8s-kzx",
    },
    {
      fnode: "应用/dasp-app-mgr-d5c7",
      snode: "MYSQL/bjb-dasp-mysql-kzx",
    },
    {
      fnode: "应用/bjc-dasp-mgr-7384",
      snode: "MYSQL/bjc-dasp-mysql-kzx",
    },
    {
      fnode: "应用/dasp-azkaban-mgr-4d86",
      snode: "MYSQL/bjb-dasp-mysql-kzx",
    },
    {
      fnode: "MYSQL/bjb-dasp-mysql-kzx",
      snode: "CANAL/bjb-dasp-canal-kzx",
    },
    {
      fnode: "MYSQL/bjc-dasp-mysql-kzx",
      snode: "CANAL/bjc-dasp-canal-kzx",
    },
    {
      fnode: "MYSQL/hfa-dasp-mysql-kzx",
      snode: "CANAL/hfa-dasp-canal-kzx",
    },
    {
      fnode: "CANAL/bjb-dasp-canal-kzx",
      snode: "KAFKA/bjb-dasp-kafka-kzx",
    },
    {
      fnode: "CANAL/bjc-dasp-canal-kzx",
      snode: "KAFKA/bjc-dasp-kafka-kzx",
    },
    {
      fnode: "CANAL/hfa-dasp-canal-kzx",
      snode: "KAFKA/hfa-dasp-kafka-kzx",
    },
    {
      fnode: "KAFKA/bjb-dasp-kafka-kzx",
      snode: "ZOOKEEPER/bjb-dasp-zk-kzx",
    },
    {
      fnode: "KAFKA/bjb-dasp-kafka-kzx",
      snode: "ES/bjb-dasp-es-kzx",
    },
    {
      fnode: "KAFKA/bjb-dasp-kafka-kzx",
      snode: "GREATDB/bjb-dasp-greatdb-kzx",
    },
    {
      fnode: "KAFKA/bjb-dasp-kafka-kzx",
      snode: "HADOOP/bjb-dasp-hadoop-kzx",
    },
    {
      fnode: "ZOOKEEPER/bjb-dasp-zk-kzx",
      snode: "KAFKA/bjb-dasp-kafka-kzx",
    },
    {
      fnode: "ES/bjb-dasp-es-kzx",
      snode: "GREATDB/bjb-dasp-greatdb-kzx",
    },
  ],
  集群关系: {
    CANAL: [
      {
        clusterName: "dasp-canal-kzx",
        nodes: [
          "bjb-dasp-canal-kzx",
          "bjc-dasp-canal-kzx",
          "hfa-dasp-canal-kzx",
        ],
        desc: "Canal集群用于数据同步，支持MySQL、Oracle等数据库的binlog解析和数据传输。",
      },
      {
        clusterName: "dasp-canal-kzx",
        nodes: [
          "bjb-dasp-canal-kzx",
          "bjc-dasp-canal-kzx",
          "hfa-dasp-canal-kzx",
        ],
        desc: "Canal集群用于数据同步，支持MySQL、Oracle等数据库的binlog解析和数据传输。",
      },
    ],
    ES: [
      {
        clusterName: "dasp-es-kzx",
        nodes: ["bjb-dasp-es-kzx", "bjc-dasp-es-kzx", "hfa-dasp-es-kzx"],
      },
    ],
    // GREATDB: [
    //   {
    //     clusterName: "dasp-greatdb-kzx",
    //     nodes: [
    //       "bjb-dasp-greatdb-kzx",
    //       "bjc-dasp-greatdb-kzx",
    //       "hfa-dasp-greatdb-kzx",
    //     ],
    //   },
    // ],
    // HADOOP: [
    //   {
    //     clusterName: "dasp-hadoop-kzx",
    //     nodes: ["bjb-dasp-hadoop-kzx", "hfa-dasp-hadoop-kzx"],
    //   },
    // ],
    // HAPROXY: [
    //   {
    //     clusterName: "dasp-haproxy-ht",
    //     nodes: ["dasp_ht_haproxy_4", "dasp_ht_haproxy_5"],
    //   },
    //   {
    //     clusterName: "dasp-haproxy-cym",
    //     nodes: ["dasp_cym_haproxy_4", "dasp_cym_haproxy_8"],
    //   },
    // ],
    // KAFKA: [
    //   {
    //     clusterName: "dasp-kafka-kzx",
    //     nodes: [
    //       "bjb-dasp-kafka-kzx",
    //       "bjc-dasp-kafka-kzx",
    //       "hfa-dasp-kafka-kzx",
    //     ],
    //   },
    // ],
    // MYSQL: [
    //   {
    //     clusterName: "dasp-mysql-kzx",
    //     nodes: [
    //       "bjb-dasp-mysql-kzx",
    //       "bjc-dasp-mysql-kzx",
    //       "hfa-dasp-mysql-kzx",
    //     ],
    //   },
    // ],
    // // NGINX: [
    // //   {
    // //     clusterName: "dasp-nginx-kzx",
    // //     nodes: [
    // //       "bjb-dasp-nginx-kzx",
    // //       "bjc-dasp-nginx-kzx",
    // //       "hfa-dasp-nginx-kzx",
    // //     ],
    // //   },
    // // ],
    // ZOOKEEPER: [
    //   {
    //     clusterName: "dasp-zk-kzx",
    //     nodes: ["bjb-dasp-zk-kzx", "bjc-dasp-zk-kzx", "hfa-dasp-zk-kzx"],
    //   },
    // ],
    // RSYNC: [
    //   {
    //     clusterName: "dasp-rsync-kzx",
    //     nodes: ["bjb-dasp-rsync-kzx", "bjc-dasp-rsync-kzx"],
    //   },
    // ],
    // 容器云: [
    //   {
    //     clusterName: "dasp-k8s-kzx",
    //     nodes: ["bjb-dasp-k8s-kzx", "bjc-dasp-k8s-kzx", "hfa-dasp-k8s-kzx"],
    //   },
    // ],
    // 应用: [
    //   {
    //     clusterName: "dasp-app-mgr-cluster",
    //     nodes: [
    //       "dasp-azkaban-mgr-4d86",
    //       "dasp-app-mgr-d5c7",
    //       "bjc-dasp-mgr-7384",
    //       "bjc-dasp-mgr-3174",
    //     ],
    //   },
    // ],
  },
};

let explistRes = {
  指标异常: {
    HADOOP: [
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "bjc-dasp-hive-kzx-0085",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 2.99,
            code: 2,
            max: 77.8,
            min: 0.82,
            p99: 36.58,
          },
          "Filesystem space available": {
            AvailableSize: 38727.57,
            TotalSize: 101273.6746673584,
            code: 0,
            usage: 61.76,
          },
          内存使用率: {
            avg: 13.41,
            code: 1,
            max: 35.03,
            min: 12.91,
            p99: 24.86,
          },
        },
        ip: "25.131.187.85",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P7100309",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "bjc-dasp-hive-kzx-0086",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 34.66,
            code: 1,
            max: 56.1,
            min: 1.36,
            p99: 49.06,
          },
          "Filesystem space available": {
            AvailableSize: 11193.58,
            TotalSize: 405569.0809314187,
            code: 2,
            usage: 97.24,
          },
          内存使用率: {
            avg: 13.19,
            code: 0,
            max: 44.3,
            min: 11.81,
            p99: 57.29,
          },
        },
        ip: "25.131.187.86",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P71649431",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "bjc-dasp-hive-kzx-0087",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 40.41,
            code: 2,
            max: 82.9,
            min: 0.62,
            p99: 50.65,
          },
          "Filesystem space available": {
            AvailableSize: 9038.53,
            TotalSize: 18922.8468662379,
            code: 0,
            usage: 52.23,
          },
          内存使用率: {
            avg: 61.4,
            code: 1,
            max: 94,
            min: 10.77,
            p99: 94.06,
          },
        },
        ip: "25.131.187.87",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P71162892",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "bjc-dasp-hive-kzx-0088",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 38.67,
            code: 2,
            max: 94.2,
            min: 0.74,
            p99: 81.46,
          },
          "Filesystem space available": {
            AvailableSize: 58773.65,
            TotalSize: 70678.3438008194,
            code: 0,
            usage: 16.84,
          },
          内存使用率: {
            avg: 72.32,
            code: 1,
            max: 81.1,
            min: 42.86,
            p99: 81.54,
          },
        },
        ip: "25.131.187.88",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P71639813",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "bjc-dasp-hive-kzx-0089",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 41.25,
            code: 2,
            max: 93.1,
            min: 3.41,
            p99: 89.57,
          },
          "Filesystem space available": {
            AvailableSize: 53040.82,
            TotalSize: 69101.2549082154,
            code: 0,
            usage: 23.24,
          },
          内存使用率: {
            avg: 25.45,
            code: 0,
            max: 47.7,
            min: 44.49,
            p99: 37.04,
          },
        },
        ip: "25.131.187.89",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P71272804",
      },
      {
        component: "dasp-hadoop",
        cpu: 32,
        hostname: "bjc-dasp-hive-kzx-0090",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 29.83,
            code: 2,
            max: 98.9,
            min: 4.12,
            p99: 48.64,
          },
          "Filesystem space available": {
            AvailableSize: 57202.17,
            TotalSize: 72847.5684566115,
            code: 0,
            usage: 21.48,
          },
          内存使用率: {
            avg: 81.13,
            code: 1,
            max: 97.2,
            min: 29.13,
            p99: 94.67,
          },
        },
        ip: "25.131.187.90",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P71359095",
      },
      {
        component: "dasp-hadoop",
        cpu: 32,
        hostname: "bjc-dasp-hive-kzx-0091",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 32.99,
            code: 2,
            max: 94.4,
            min: 5.49,
            p99: 53.94,
          },
          "Filesystem space available": {
            AvailableSize: 55192.39,
            TotalSize: 282127.1829301529,
            code: 1,
            usage: 80.44,
          },
          内存使用率: {
            avg: 74.49,
            code: 1,
            max: 83.1,
            min: 5.94,
            p99: 95.31,
          },
        },
        ip: "25.131.187.91",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P71557286",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "bjc-dasp-hive-kzx-0092",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 25.56,
            code: 2,
            max: 83.6,
            min: 2.51,
            p99: 52.51,
          },
          "Filesystem space available": {
            AvailableSize: 9448.89,
            TotalSize: 16302.399226342,
            code: 0,
            usage: 42.04,
          },
          内存使用率: {
            avg: 64.47,
            code: 1,
            max: 90.3,
            min: 39.05,
            p99: 87.72,
          },
        },
        ip: "25.131.187.92",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P71453787",
      },
      {
        component: "dasp-hadoop",
        cpu: 32,
        hostname: "bjc-dasp-hive-kzx-0093",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 2.9,
            code: 0,
            max: 7.1,
            min: 5.1,
            p99: 11.57,
          },
          "Filesystem space available": {
            AvailableSize: 44080.01,
            TotalSize: 50689.6737424429,
            code: 0,
            usage: 13.04,
          },
          内存使用率: {
            avg: 83.05,
            code: 2,
            max: 95.3,
            min: 43.7,
            p99: 93.02,
          },
        },
        ip: "25.131.187.93",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P71024118",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "bjc-dasp-hive-kzx-0094",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 59.74,
            code: 2,
            max: 85.3,
            min: 2.09,
            p99: 74.89,
          },
          "Filesystem space available": {
            AvailableSize: 23024.66,
            TotalSize: 224946.1694977737,
            code: 1,
            usage: 89.76,
          },
          内存使用率: {
            avg: 87.94,
            code: 1,
            max: 73.4,
            min: 8.44,
            p99: 83.84,
          },
        },
        ip: "25.131.187.94",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P71946759",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "bjc-dasp-hive-kzx-0095",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 52.56,
            code: 1,
            max: 79.1,
            min: 3.73,
            p99: 41.6,
          },
          "Filesystem space available": {
            AvailableSize: 25105.1,
            TotalSize: 586312.4333217832,
            code: 2,
            usage: 95.72,
          },
          内存使用率: {
            avg: 18.7,
            code: 0,
            max: 63.5,
            min: 43.9,
            p99: 60.31,
          },
        },
        ip: "25.131.187.95",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P715865610",
      },
      {
        component: "dasp-hadoop",
        cpu: 32,
        hostname: "bjc-dasp-hive-kzx-0096",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 47.99,
            code: 2,
            max: 93.5,
            min: 0.18,
            p99: 62.67,
          },
          "Filesystem space available": {
            AvailableSize: 57855.58,
            TotalSize: 102514.6618019346,
            code: 0,
            usage: 43.56,
          },
          内存使用率: {
            avg: 71.33,
            code: 1,
            max: 93.6,
            min: 39.35,
            p99: 83.16,
          },
        },
        ip: "25.131.187.96",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P718583711",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "bjc-dasp-hive-kzx-0097",
        idc: "BJ-DB",
        inspect_data: {
          CPU使用率: {
            avg: 1.65,
            code: 0,
            max: 12,
            min: 2.81,
            p99: 11.49,
          },
          "Filesystem space available": {
            AvailableSize: 10355.65,
            TotalSize: 16129.7519566618,
            code: 0,
            usage: 35.8,
          },
          内存使用率: {
            avg: 20.61,
            code: 0,
            max: 52.6,
            min: 7.42,
            p99: 37.81,
          },
        },
        ip: "25.131.187.97",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-DB/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P712957212",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "bjb-dasp-hive-kzx-0101",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 33.56,
            code: 2,
            max: 91.7,
            min: 0.8,
            p99: 83.2,
          },
          "Filesystem space available": {
            AvailableSize: 53019.37,
            TotalSize: 264595.5708018808,
            code: 1,
            usage: 79.96,
          },
          内存使用率: {
            avg: 76.19,
            code: 1,
            max: 89.6,
            min: 16.89,
            p99: 79.97,
          },
        },
        ip: "25.131.186.101",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P711940413",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "bjb-dasp-hive-kzx-0102",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 31.24,
            code: 2,
            max: 92.4,
            min: 1.74,
            p99: 57.54,
          },
          "Filesystem space available": {
            AvailableSize: 15125.16,
            TotalSize: 20816.3137835998,
            code: 0,
            usage: 27.34,
          },
          内存使用率: {
            avg: 62.27,
            code: 1,
            max: 83.4,
            min: 14.2,
            p99: 66.73,
          },
        },
        ip: "25.131.186.102",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P719069214",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "bjb-dasp-hive-kzx-0103",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 30.79,
            code: 2,
            max: 87.8,
            min: 1.17,
            p99: 74.56,
          },
          "Filesystem space available": {
            AvailableSize: 6588.45,
            TotalSize: 14281.7331215755,
            code: 0,
            usage: 53.87,
          },
          内存使用率: {
            avg: 52.92,
            code: 1,
            max: 92.3,
            min: 18.4,
            p99: 88.03,
          },
        },
        ip: "25.131.186.103",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P718354515",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "bjb-dasp-hive-kzx-0104",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 37.48,
            code: 2,
            max: 84.3,
            min: 4.58,
            p99: 60.84,
          },
          "Filesystem space available": {
            AvailableSize: 33960.28,
            TotalSize: 50569.6727297274,
            code: 0,
            usage: 32.84,
          },
          内存使用率: {
            avg: 60.27,
            code: 1,
            max: 96.6,
            min: 14.91,
            p99: 80.44,
          },
        },
        ip: "25.131.186.104",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P715426416",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "bjb-dasp-hive-kzx-0105",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 35.71,
            code: 2,
            max: 97.7,
            min: 1.49,
            p99: 82.75,
          },
          "Filesystem space available": {
            AvailableSize: 26925.04,
            TotalSize: 31785.8906607423,
            code: 0,
            usage: 15.29,
          },
          内存使用率: {
            avg: 68.78,
            code: 1,
            max: 85.5,
            min: 33.66,
            p99: 69.69,
          },
        },
        ip: "25.131.186.105",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P718319417",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "bjb-dasp-hive-kzx-0106",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 53.54,
            code: 2,
            max: 83.5,
            min: 1.5,
            p99: 88.76,
          },
          "Filesystem space available": {
            AvailableSize: 50639.67,
            TotalSize: 566488.2337846125,
            code: 1,
            usage: 91.06,
          },
          内存使用率: {
            avg: 72.47,
            code: 1,
            max: 72,
            min: 12.66,
            p99: 81.57,
          },
        },
        ip: "25.131.186.106",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P718886818",
      },
      {
        component: "dasp-hadoop",
        cpu: 32,
        hostname: "bjb-dasp-hive-kzx-0107",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 30.63,
            code: 1,
            max: 91.9,
            min: 3.7,
            p99: 38.63,
          },
          "Filesystem space available": {
            AvailableSize: 18986.98,
            TotalSize: 25954.6453632634,
            code: 0,
            usage: 26.85,
          },
          内存使用率: {
            avg: 88.49,
            code: 1,
            max: 82.9,
            min: 15.32,
            p99: 86.84,
          },
        },
        ip: "25.131.186.107",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P719143919",
      },
      {
        component: "dasp-hadoop",
        cpu: 32,
        hostname: "bjb-dasp-hive-kzx-0108",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 36.1,
            code: 2,
            max: 86.5,
            min: 4.65,
            p99: 59,
          },
          "Filesystem space available": {
            AvailableSize: 12881.53,
            TotalSize: 17752.3212465568,
            code: 0,
            usage: 27.44,
          },
          内存使用率: {
            avg: 79.29,
            code: 1,
            max: 97.4,
            min: 26.56,
            p99: 86.8,
          },
        },
        ip: "25.131.186.108",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P717424420",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "bjb-dasp-hive-kzx-0109",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 27.95,
            code: 2,
            max: 83,
            min: 2.32,
            p99: 61.24,
          },
          "Filesystem space available": {
            AvailableSize: 21574.46,
            TotalSize: 49974.2536959261,
            code: 0,
            usage: 56.83,
          },
          内存使用率: {
            avg: 58.57,
            code: 1,
            max: 73.4,
            min: 31.35,
            p99: 84.15,
          },
        },
        ip: "25.131.186.109",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P717372421",
      },
      {
        component: "dasp-hadoop",
        cpu: 32,
        hostname: "bjb-dasp-hive-kzx-0110",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 28.37,
            code: 1,
            max: 78.3,
            min: 1.58,
            p99: 52.97,
          },
          "Filesystem space available": {
            AvailableSize: 9180.58,
            TotalSize: 28331.363421019,
            code: 0,
            usage: 67.6,
          },
          内存使用率: {
            avg: 74.65,
            code: 2,
            max: 98.8,
            min: 18.62,
            p99: 87.08,
          },
        },
        ip: "25.131.186.110",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P711725022",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "bjb-dasp-hive-kzx-0111",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 54.37,
            code: 2,
            max: 87.7,
            min: 2.87,
            p99: 79.1,
          },
          "Filesystem space available": {
            AvailableSize: 57259.92,
            TotalSize: 138064.2464702012,
            code: 0,
            usage: 58.53,
          },
          内存使用率: {
            avg: 74.47,
            code: 2,
            max: 92.8,
            min: 39.86,
            p99: 97.69,
          },
        },
        ip: "25.131.186.111",
        memory: 256,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P710310123",
      },
      {
        component: "dasp-hadoop",
        cpu: 32,
        hostname: "bjb-dasp-hive-kzx-0112",
        idc: "BJ-NFX",
        inspect_data: {
          CPU使用率: {
            avg: 8.31,
            code: 1,
            max: 90.6,
            min: 4.1,
            p99: 82.81,
          },
          "Filesystem space available": {
            AvailableSize: 11458.89,
            TotalSize: 32841.9939302474,
            code: 0,
            usage: 65.11,
          },
          内存使用率: {
            avg: 86.55,
            code: 2,
            max: 91.1,
            min: 6.67,
            p99: 91.03,
          },
        },
        ip: "25.131.186.112",
        memory: 512,
        mtype: "p",
        net_zone_code: "BJ-NFX/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P713599824",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "hfa-dasp-hive-kzx-0201",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 55.86,
            code: 1,
            max: 82.2,
            min: 1.43,
            p99: 64.24,
          },
          "Filesystem space available": {
            AvailableSize: 48983.47,
            TotalSize: 1789821.2301151827,
            code: 1,
            usage: 97.26,
          },
          内存使用率: {
            avg: 53.3,
            code: 1,
            max: 85.4,
            min: 33.23,
            p99: 83.52,
          },
        },
        ip: "25.131.185.201",
        memory: 512,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P715883425",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "hfa-dasp-hive-kzx-0202",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 44.32,
            code: 2,
            max: 85.8,
            min: 4.77,
            p99: 45.16,
          },
          "Filesystem space available": {
            AvailableSize: 31045.41,
            TotalSize: 514371.1305810201,
            code: 1,
            usage: 93.96,
          },
          内存使用率: {
            avg: 81.19,
            code: 2,
            max: 90.1,
            min: 19.84,
            p99: 97.72,
          },
        },
        ip: "25.131.185.202",
        memory: 512,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P715614626",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "hfa-dasp-hive-kzx-0203",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 42.23,
            code: 1,
            max: 93.5,
            min: 2.47,
            p99: 27.41,
          },
          "Filesystem space available": {
            AvailableSize: 54613.72,
            TotalSize: 173370.6914068395,
            code: 0,
            usage: 68.5,
          },
          内存使用率: {
            avg: 57.05,
            code: 1,
            max: 74,
            min: 22.81,
            p99: 70.98,
          },
        },
        ip: "25.131.185.203",
        memory: 256,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P713109027",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "hfa-dasp-hive-kzx-0204",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 29.19,
            code: 2,
            max: 90.2,
            min: 5.94,
            p99: 79.61,
          },
          "Filesystem space available": {
            AvailableSize: 33261.17,
            TotalSize: 227570.2748016611,
            code: 1,
            usage: 85.38,
          },
          内存使用率: {
            avg: 31.7,
            code: 0,
            max: 57,
            min: 42.16,
            p99: 30.64,
          },
        },
        ip: "25.131.185.204",
        memory: 512,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P712735128",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "hfa-dasp-hive-kzx-0205",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 39.54,
            code: 1,
            max: 77.7,
            min: 1.48,
            p99: 58.16,
          },
          "Filesystem space available": {
            AvailableSize: 9915.46,
            TotalSize: 25846.3023292869,
            code: 0,
            usage: 61.64,
          },
          内存使用率: {
            avg: 26.3,
            code: 0,
            max: 45.5,
            min: 30.18,
            p99: 33.33,
          },
        },
        ip: "25.131.185.205",
        memory: 256,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P711984829",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "hfa-dasp-hive-kzx-0206",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 35.64,
            code: 2,
            max: 90.8,
            min: 5.28,
            p99: 72.49,
          },
          "Filesystem space available": {
            AvailableSize: 9586.81,
            TotalSize: 14395.5588236547,
            code: 0,
            usage: 33.4,
          },
          内存使用率: {
            avg: 76.56,
            code: 2,
            max: 94.7,
            min: 30.14,
            p99: 89.66,
          },
        },
        ip: "25.131.185.206",
        memory: 512,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P710004330",
      },
      {
        component: "dasp-hadoop",
        cpu: 32,
        hostname: "hfa-dasp-hive-kzx-0207",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 41.06,
            code: 2,
            max: 82.2,
            min: 3.63,
            p99: 76.18,
          },
          "Filesystem space available": {
            AvailableSize: 26188.45,
            TotalSize: 53261.1272230167,
            code: 0,
            usage: 50.83,
          },
          内存使用率: {
            avg: 78.1,
            code: 2,
            max: 95.9,
            min: 20.01,
            p99: 90.92,
          },
        },
        ip: "25.131.185.207",
        memory: 256,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P715567131",
      },
      {
        component: "dasp-hadoop",
        cpu: 32,
        hostname: "hfa-dasp-hive-kzx-0208",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 24.28,
            code: 1,
            max: 97.6,
            min: 2.51,
            p99: 31.42,
          },
          "Filesystem space available": {
            AvailableSize: 11367.31,
            TotalSize: 16616.852209356,
            code: 0,
            usage: 31.59,
          },
          内存使用率: {
            avg: 34.28,
            code: 0,
            max: 36,
            min: 30.9,
            p99: 36.02,
          },
        },
        ip: "25.131.185.208",
        memory: 256,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P717804732",
      },
      {
        component: "dasp-hadoop",
        cpu: 64,
        hostname: "hfa-dasp-hive-kzx-0209",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 44.1,
            code: 2,
            max: 98.4,
            min: 0.64,
            p99: 73.96,
          },
          "Filesystem space available": {
            AvailableSize: 9483.2,
            TotalSize: 12565.6568158824,
            code: 0,
            usage: 24.53,
          },
          内存使用率: {
            avg: 32.56,
            code: 0,
            max: 35.4,
            min: 37.44,
            p99: 35.5,
          },
        },
        ip: "25.131.185.209",
        memory: 256,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P714055633",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "hfa-dasp-hive-kzx-0210",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 26.5,
            code: 2,
            max: 98.8,
            min: 2.15,
            p99: 83.3,
          },
          "Filesystem space available": {
            AvailableSize: 12860.47,
            TotalSize: 18595.4454920646,
            code: 0,
            usage: 30.84,
          },
          内存使用率: {
            avg: 27.94,
            code: 0,
            max: 60.1,
            min: 29.45,
            p99: 37.95,
          },
        },
        ip: "25.131.185.210",
        memory: 256,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P710374634",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "hfa-dasp-hive-kzx-0211",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 52.22,
            code: 1,
            max: 83.7,
            min: 4.64,
            p99: 68.18,
          },
          "Filesystem space available": {
            AvailableSize: 7509.65,
            TotalSize: 17194.933418092,
            code: 0,
            usage: 56.33,
          },
          内存使用率: {
            avg: 90.36,
            code: 2,
            max: 90.4,
            min: 5.77,
            p99: 94.59,
          },
        },
        ip: "25.131.185.211",
        memory: 512,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P711293535",
      },
      {
        component: "dasp-hadoop",
        cpu: 96,
        hostname: "hfa-dasp-hive-kzx-0212",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 38.43,
            code: 1,
            max: 69.1,
            min: 5.96,
            p99: 49.43,
          },
          "Filesystem space available": {
            AvailableSize: 21874.47,
            TotalSize: 55924.8174288072,
            code: 0,
            usage: 60.89,
          },
          内存使用率: {
            avg: 65.42,
            code: 1,
            max: 84.8,
            min: 24.65,
            p99: 66.3,
          },
        },
        ip: "25.131.185.212",
        memory: 512,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P716472236",
      },
      {
        component: "dasp-hadoop",
        cpu: 32,
        hostname: "hfa-dasp-hive-kzx-0213",
        idc: "HF",
        inspect_data: {
          CPU使用率: {
            avg: 45.51,
            code: 2,
            max: 95.9,
            min: 0.61,
            p99: 62.51,
          },
          "Filesystem space available": {
            AvailableSize: 25665.97,
            TotalSize: 64419.7539174994,
            code: 0,
            usage: 60.16,
          },
          内存使用率: {
            avg: 59.81,
            code: 1,
            max: 72,
            min: 32.02,
            p99: 91.2,
          },
        },
        ip: "25.131.185.213",
        memory: 512,
        mtype: "p",
        net_zone_code: "HF/HCS/YN/HXYW",
        os: "Kylin Linux Advanced Server V10 64bit",
        sn: "2102313AUXN0P712704337",
      },
    ],
    应用: [
      {
        component: "dasp-ps-transfer",
        cpu: "2",
        hostname: "sza-dasp-transfer-kzx-0002",
        idc: "SZ-NW",
        inspect_data: {
          CPU使用率: {
            avg: 2.99,
            code: 2,
            max: 77.8,
            min: 0.82,
            p99: 36.58,
          },
          "Filesystem space available": {
            AvailableSize: 38727.57,
            TotalSize: 101273.6746673584,
            code: 0,
            usage: 61.76,
          },
          内存使用率: {
            avg: 13.41,
            code: 1,
            max: 35.03,
            min: 12.91,
            p99: 24.86,
          },
        },
        ip: "25.131.16.332",
        memory: 4,
        mtype: "v",
        net_zone_code: "SZ-NW/HCS/FABRIC_SC/WL",
        os: "Kylin Linux Advanced Server release V10 (Tercel)",
      },
      {
        component: "dasp-ps-account",
        cpu: "4",
        hostname: "sza-dasp-account-kzx-0001",
        idc: "SZ-NW",
        inspect_data: {
          CPU使用率: {
            avg: 59.23,
            code: 2,
            max: 83.5,
            min: 3.73,
            p99: 83,
          },
          "Filesystem space available": {
            AvailableSize: 55073.67,
            TotalSize: 105156.5983858067,
            code: 0,
            usage: 47.63,
          },
          内存使用率: {
            avg: 21.46,
            code: 0,
            max: 44.8,
            min: 25.76,
            p99: 52.09,
          },
        },
        ip: "25.131.16.121",
        memory: 8,
        mtype: "v",
        net_zone_code: "SZ-NW/HCS/FABRIC_SC/WL",
        os: "Kylin Linux Advanced Server release V10 (Tercel)",
      },
      {
        component: "dasp-ps-card",
        cpu: "4",
        hostname: "sza-dasp-card-kzx-0003",
        idc: "SZ-NW",
        inspect_data: {
          CPU使用率: {
            avg: 50.78,
            code: 2,
            max: 83,
            min: 4.01,
            p99: 53.12,
          },
          "Filesystem space available": {
            AvailableSize: 9636,
            TotalSize: 18222.5888534982,
            code: 0,
            usage: 47.12,
          },
          内存使用率: {
            avg: 84.64,
            code: 2,
            max: 96,
            min: 33.6,
            p99: 95.16,
          },
        },
        ip: "25.131.16.122",
        memory: 8,
        mtype: "v",
        net_zone_code: "SZ-NW/HCS/FABRIC_SC/WL",
        os: "Kylin Linux Advanced Server release V10 (Tercel)",
      },
      {
        component: "dasp-ps-bill",
        cpu: "8",
        hostname: "sza-dasp-bill-kzx-0004",
        idc: "SZ-NW",
        inspect_data: {
          CPU使用率: {
            avg: 58.89,
            code: 2,
            max: 86.4,
            min: 3.17,
            p99: 81.73,
          },
          "Filesystem space available": {
            AvailableSize: 27212.5,
            TotalSize: 38605.5784396057,
            code: 0,
            usage: 29.51,
          },
          内存使用率: {
            avg: 63.51,
            code: 1,
            max: 79.4,
            min: 8.48,
            p99: 75.12,
          },
        },
        ip: "25.131.16.123",
        memory: 16,
        mtype: "v",
        net_zone_code: "SZ-NW/HCS/FABRIC_SC/WL",
        os: "Kylin Linux Advanced Server release V10 (Tercel)",
      },
      {
        component: "dasp-ps-risk",
        cpu: "8",
        hostname: "sza-dasp-risk-kzx-0005",
        idc: "SZ-NW",
        inspect_data: {
          CPU使用率: {
            avg: 27.16,
            code: 2,
            max: 96.5,
            min: 5.02,
            p99: 81.32,
          },
          "Filesystem space available": {
            AvailableSize: 17539.72,
            TotalSize: 54986.7379602685,
            code: 0,
            usage: 68.1,
          },
          内存使用率: {
            avg: 93.95,
            code: 1,
            max: 90.7,
            min: 37.23,
            p99: 76.61,
          },
        },
        ip: "25.131.16.124",
        memory: 16,
        mtype: "v",
        net_zone_code: "SZ-NW/HCS/FABRIC_SC/WL",
        os: "Kylin Linux Advanced Server release V10 (Tercel)",
      },
      {
        component: "dasp-ps-msg",
        cpu: "8",
        hostname: "sza-dasp-msg-kzx-0006",
        idc: "SZ-NW",
        inspect_data: {
          CPU使用率: {
            avg: 58.05,
            code: 1,
            max: 58.9,
            min: 0.92,
            p99: 35.2,
          },
          "Filesystem space available": {
            AvailableSize: 54696.84,
            TotalSize: 417434.0560847195,
            code: 1,
            usage: 86.9,
          },
          内存使用率: {
            avg: 85.02,
            code: 1,
            max: 89.3,
            min: 38.12,
            p99: 89.03,
          },
        },
        ip: "25.131.16.125",
        memory: 16,
        mtype: "v",
        net_zone_code: "SZ-NW/HCS/FABRIC_SC/WL",
        os: "Kylin Linux Advanced Server release V10 (Tercel)",
      },
    ],
  },
  采集异常: {
    数据: {
      REDIS: [
        {
          desc: "数据集为空",
          ip: "192.168.12.156",
        },
        {
          desc: "数据集为空",
          ip: "192.168.12.155",
        },
        {
          desc: "指标：内存使用率数据为空",
          ip: "192.168.12.154",
        },
      ],
      应用: [
        {
          desc: "数据集为空",
          ip: "192.168.231.24",
        },
        {
          desc: "数据集为空",
          ip: "192.168.231.25",
        },
      ],
    },
    采集日期: "2026-08-31",
  },
};

export { billRes, systemProfileRes, explistRes };
